- AT_LEAST_ONE: input_max_length
- AT_LEAST_ONE: model_hp_initializer_gain
- AT_LEAST_ONE: model_hp_hidden_layers
- AT_LEAST_ONE: model_hp_embedding_shared_weights
- AT_LEAST_ONE: model_hp_attention_dense
- AT_LEAST_ONE: model_hp_attention_dropout
- AT_LEAST_ONE: model_hp_ffn_output_dense
- AT_LEAST_ONE: model_hp_ffn_filter_dense
- AT_LEAST_ONE: model_hp_relu_dropout
- AT_LEAST_ONE: model_hp_layer_postprocess_dropout
- AT_LEAST_ONE: model_hp_norm
- AT_LEAST_ONE: model_hp_sequence_beam_search

