- AT_LEAST_ONE: backbone
- AT_LEAST_ONE: feature_sizes
- AT_LEAST_ONE: steps
- AT_LEAST_ONE: scales
- AT_LEAST_ONE: aspect_ratios
- AT_LEAST_ONE: num_defaults_per_cell
- AT_LEAST_ONE: loc_conf_out_channels
- AT_LEAST_ONE: num_default_boxes
- AT_LEAST_ONE: nms_threshold
- AT_LEAST_ONE: nms_max_detections
- AT_LEAST_ONE: num_cropping_iterations
- AT_LEAST_ONE: random_flip_probability
- AT_LEAST_ONE: data_normalization_mean
- AT_LEAST_ONE: data_normalization_std
