// __TRITON_AOT_GENERATE_BEGIN__ HEADER_INCLUDE
#include "kernel.h"
// __TRITON_AOT_GENERATE_END__ HEADER_INCLUDE
// These headers are used by code generated at runtime in KERNEL_SPECS blocks
#include <torch/csrc/stable/accelerator.h>
#include <torch/headeronly/core/ScalarType.h> // NOLINT(facebook-unused-include-check)

inline void triton_aot_cu_check(CUresult err, const char* file, int line) {
  if (err != CUDA_SUCCESS) {
    const char* err_str;
    cuGetErrorString(err, &err_str);
    throw std::runtime_error(
        std::string(file) + ":" + std::to_string(line) +
        " CUDA driver error: " + (err_str ? err_str : "unknown"));
  }
}
#define TRITON_AOT_CU_CHECK(EXPR) triton_aot_cu_check(EXPR, __FILE__, __LINE__)

// NOLINTNEXTLINE(facebook-hte-NullableReturn): error path throws
inline cudaStream_t triton_aot_get_current_stream() {
  auto device_idx = torch::stable::accelerator::getCurrentDeviceIndex();
  void* stream_ptr = nullptr;
  // TODO: No torch::stable op provides the same functionality
  // today. Revisit if torch exposes a proper stable::accelerator stream API.
  if (aoti_torch_get_current_cuda_stream(device_idx, &stream_ptr) != 0) {
    throw std::runtime_error("Failed to get current CUDA stream");
  }
  return reinterpret_cast<cudaStream_t>(stream_ptr);
}

namespace triton {
namespace aot {

namespace {
[[maybe_unused]] int compute_capability() {
  // Cached: AOTT hosts use homogeneous GPUs.
  static int cc = 0;
  if (cc == 0) {
    CUdevice device;
    TRITON_AOT_CU_CHECK(cuCtxGetDevice(&device));
    int major, minor;
    TRITON_AOT_CU_CHECK(cuDeviceGetAttribute(
        &major, CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MAJOR, device));
    TRITON_AOT_CU_CHECK(cuDeviceGetAttribute(
        &minor, CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MINOR, device));
    cc = major * 10 + minor;
  }
  return cc;
}
} // namespace

namespace {
#ifdef USE_ROCM
[[maybe_unused]] void check_errors(int shared, hipFunction_t func) {
  // HIP doesn't need the same shared memory configuration as CUDA
  return;
}
#else
[[maybe_unused]] void check_errors(int shared, CUfunction func) {
  int shared_optin;
  int device = 0;
  TRITON_AOT_CU_CHECK(cuDeviceGetAttribute(
      &shared_optin,
      CU_DEVICE_ATTRIBUTE_MAX_SHARED_MEMORY_PER_BLOCK_OPTIN,
      device));
  if (shared > 49152 && shared_optin > 49152) {
    // If requested/shared_optin exceed 48 KB, it switches cache to prefer
    // shared memory and sets the max dynamic shared memory so the kernel can
    // allocate the larger amount needed.
    TRITON_AOT_CU_CHECK(
        cuFuncSetCacheConfig(func, CU_FUNC_CACHE_PREFER_SHARED));
    int shared_total, shared_static;
    TRITON_AOT_CU_CHECK(cuDeviceGetAttribute(
        &shared_total,
        CU_DEVICE_ATTRIBUTE_MAX_SHARED_MEMORY_PER_MULTIPROCESSOR,
        device));
    TRITON_AOT_CU_CHECK(cuFuncGetAttribute(
        &shared_static, CU_FUNC_ATTRIBUTE_SHARED_SIZE_BYTES, func));
    TRITON_AOT_CU_CHECK(cuFuncSetAttribute(
        func,
        CU_FUNC_ATTRIBUTE_MAX_DYNAMIC_SHARED_SIZE_BYTES,
        shared_optin - shared_static));
  }
}
#endif
} // namespace

// __TRITON_AOT_GENERATE_BEGIN__ KERNEL_SPECS
// __TRITON_AOT_GENERATE_END__ KERNEL_SPECS

// __TRITON_AOT_GENERATE_BEGIN__ SELECTOR
// __TRITON_AOT_GENERATE_END__ SELECTOR

} // namespace aot
} // namespace triton

// Anchor: keeps the inline `triton_aot_get_current_stream` (and its reference
// to `aoti_torch_get_current_cuda_stream`) from being dead-stripped at
// buck-build time, where KERNEL_SPECS is empty. `weak` dedups the symbol
// across the per-op .so files generated by the runtime template substitution.
extern "C" __attribute__((weak, visibility("default"))) cudaStream_t
__triton_aot_anchor_get_stream() {
  return triton_aot_get_current_stream();
}
