accelerate launch --config_file configs/default_config.yaml scripts/train.py \
--dataset_path "./dataset" \
--model_path "/software/users/ihubara/lora_clean/llama-v2-fused-qkv" \
--max_seq_len 8192 \
--bf16 True \
--logging_steps 32 \
--eval_steps 64 \
--output_dir "./results/llama-70b_scrolls_gov_report_r16_$1" \
--per_device_train_batch_size 1 \
--gradient_accumulation_steps 1 \
--lr_scheduler_type "cosine" \
--learning_rate 5e-4 \
--warmup_ratio 0 \
--use_gradient_checkpointing True \
--target_eval_loss 0.925 \
--use_peft_lora True \
--lora_r 16 \
--lora_alpha 16 \
--lora_dropout 0.1 \
--max_steps 800 \
--use_flash_attn \
--seed "$1" \
--lora_target_modules "qkv_proj,o_proj"
