FROM python:3.8

RUN pip install https://storage.googleapis.com/cloud-tpu-tpuvm-artifacts/tensorflow/tf-2.10.0/tensorflow-2.10.0-cp38-cp38-linux_x86_64.whl
RUN curl -L https://storage.googleapis.com/cloud-tpu-tpuvm-artifacts/libtpu/1.4.0/libtpu.so -o /lib/libtpu.so
RUN apt-get update \
 && apt-get install -y --no-install-recommends \
        git libcurl4 wget unzip \
 && rm -rf /var/lib/apt/lists/*

# Install python dependencies
COPY requirements.txt /
RUN pip install --no-cache-dir -r /requirements.txt

# Copy code
COPY . /workspace/bert

RUN chmod +x /workspace/bert/cleanup_scripts/*.sh
RUN chmod +x /workspace/bert/*.sh

# Set working directory
WORKDIR /workspace/bert
